version: '3.8'
services:
  postfix:
    image: mrelay_postfix:latest
    build:
      context: postfix
      dockerfile: Dockerfile
    container_name: mrelay_postfix
    restart: always
    environment:
      MRELAY_CERTBOT_EMAIL: ${MRELAY_CERTBOT_EMAIL}
      MRELAY_POSTFIX_DOMAIN: ${MRELAY_POSTFIX_DOMAIN}
      MRELAY_POSTFIX_HOSTNAME: ${MRELAY_POSTFIX_HOSTNAME}
      MRELAY_POSTFIX_RELAYHOST: ${MRELAY_POSTFIX_RELAYHOST}
      MRELAY_CLOUDFLARE_API_KEY: ${MRELAY_CLOUDFLARE_API_KEY}
    ports:
      - "25:25"
    volumes:
      - ./mount/postfix:/var/spool/postfix
      - ./mount/letsencrypt:/etc/letsencrypt
      - ./mount/logs:/var/log