version: '3.8'
services:
  postfix:
    image: ${DOCKER_REGISTRY}/mrelay_postfix:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MRELAY_TIMEZONE: ${MRELAY_TIMEZONE}
    container_name: mrelay_postfix
    hostname: ${MRELAY_POSTFIX_HOSTNAME}
    restart: always
    env_file:
      - ../.env
    ports:
      - "25:25"
    volumes:
      # Postfix chroot directory (required)
      - ../mount/postfix:/var/spool/postfix
      # Let's Encrypt certificates (required)
      - ../mount/letsencrypt:/etc/letsencrypt
      # DKIM private keys (required)
      - ../mount/opendkim/keys:/etc/opendkim/keys
      # Logs for audit purposes (optional)
      - ../mount/logs:/var/log
